### ISSUE TITLE
Be able to access other user profiles

### ISSUE THREAD

**Issue by pputrevu-sys** [snehabanda30/CS-546-FinalProject#54]
Have a space to access users who have completed tasks for you in order to leave reviews

**Comment by birvadpatel** [comment]
Username Links on home page which lets you access the profile of the users and leave reviews (hide edit functionality when viewing other profiles)

Moreover, if time permits, comments can also be linked to allow access to the profile of the comment poster.

**Comment by Victor-M-Giraldo** [comment]
Closed by #57
