### ISSUE TITLE
Allow user to update their profile settings

### ISSUE THREAD

**Issue by Victor-M-Giraldo** [snehabanda30/CS-546-FinalProject#6]
- Create a page and a route where the user can edit their information (Phone, email, skills, address, etc)
- This page would also display user information
- Route would probably be like profile/:userid/edit
- We want this functionality to be separate from changing your username and or password.

**Comment by j-ferber** [comment]
- Make sure this is only available to the account of the user logged in
- Will have to update Mongoose schemas for the user information
